{% set name = "radiant" %}
{% set version = "1.1.2" %}
{% set sha256 = "6daf68fcb18da8568e15cda3d6f2117856dfe55255ee98b090bbae26b6e708ed" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://zivgitlab.uni-muenster.de/domain-world/RADIANT/-/archive/{{ version }}/RADIANT-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('radiant', max_pin="x") }}

requirements:
  build:
    - cmake >=3.15
    - make
    - {{ compiler('cxx') }}
  host:
    - sqlite
    - bzip2
    - zlib
    - boost-cpp >=1.77
  run:
    - sqlite
    - bzip2
    - zlib
    - boost-cpp >=1.77
test:
  commands:
    - radiant -h

about:
  home: https://domainworld.uni-muenster.de/data/radiant-db/index.html
  license: GPLv3+
  license_file: LICENSE
  summary: Annotate proteomes with protein domains
  description: |
    This program rapidly annotates protein sequences with Pfam domains
